### ISSUE TITLE
Dependencies must precede target

### ISSUE THREAD

**Issue by lf-araujo** [pixelspark/sqlite#1]
I am trying to figure out what the problem is, but it seems simple. Under ubuntu 18.04 and swift 4.2-dev, I get the error while attempting to build catena:

```
https://github.com/pixelspark/sqlite.git @ 3.19.2: error: manifest parse error(s):
/tmp/TemporaryFile.xeP9BS.swift:8:5: error: argument 'dependencies' must precede argument 'targets'
    dependencies: [
~~~~^~~~~~~~~~~~~~~
```

**Comment by pixelspark** [comment]
Hm, swift 4.2-dev is not supported (yet). Apparently the arguments need to be swapped in the `Package.swift` file of my SQLite Swift module (https://github.com/pixelspark/sqlite) which Catena depends on. You may try to use a fork for that - if it works, happy to merge the fix there.

**Comment by lf-araujo** [comment]
Will do, thanks..
